name = "topapps-api"
main = "functions/api.js"
compatibility_date = "2023-05-18"
compatibility_flags = ["nodejs_compat"]
node_compat = true

# Add your custom domain here (once set up in Cloudflare)
routes = [
  { pattern = "topapps.store/*", zone_name = "topapps.store" }
]

[env.production]
name = "topapps-api-prod"
route = { pattern = "topapps.store/*", zone_name = "topapps.store" }
# Production-specific settings
workers_dev = false

[site]
bucket = "client/dist"

[build]
command = "./build.sh"
upload.format = "service-worker"
pages_build_output_dir = "dist/public"

# Add KV Namespace or D1 Database if needed
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-id"

