name = "topapps-api"
main = "functions/api.js"
compatibility_date = "2023-05-18"

# Add your custom domain here (once set up in Cloudflare)
# routes = [
#   { pattern = "api.topapps.store/*", zone_id = "your-zone-id" }
# ]

[site]
bucket = "dist/public"

[build]
command = "./build.sh"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "topapps"
database_id = ""  # Replace with your actual D1 database ID when deploying

[env.production]
# Production-specific settings
workers_dev = false