name = "topapps-api"
main = "functions/api.js"
compatibility_date = "2023-05-18"

# Add your custom domain here (once set up in Cloudflare)
# routes = [
#   { pattern = "api.topapps.store/*", zone_id = "your-zone-id" }
# ]

[site]
bucket = "dist/public"
pages_build_output_dir = "dist/public"

[build]
command = "./build-cloudflare.sh"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "topapps"
database_id = "8252c0e2-972e-4994-b168-d9b8f9d6fddd"  # ID real de la base de datos D1

[env.production]
# Production-specific settings
workers_dev = false

# D1 Database for production
[[env.production.d1_databases]]
binding = "DB"
database_name = "topapps"
database_id = "8252c0e2-972e-4994-b168-d9b8f9d6fddd"