# Configuration for Cloudflare D1 with Wrangler
name = "topapps"
compatibility_date = "2023-05-18"
main = "functions/api-simplified.js"
workers_dev = true

# Routes for serving the worker
routes = [
  { pattern = "api.topapps.store", zone_name = "topapps.store" }
]

# D1 Database Binding
[[d1_databases]]
binding = "DB" # The ENV binding name to your Worker
database_name = "topapps-db"
database_id = "" # Enter your actual database ID here when ready for deployment

# Environment variables your worker can access
[vars]
NODE_ENV = "production"